live_config_reload = true
shell = "tmux"

[env]
TERM = "xterm-256color"
WINIT_X11_SCALE_FACTOR = "1.0"

[colors.primary]
background = '#222436'
foreground = '#c8d3f5'

[colors.normal]
black = '#1b1d2b'
red = '#ff757f'
green = '#c3e88d'
yellow = '#ffc777'
blue = '#82aaff'
magenta = '#c099ff'
cyan = '#86e1fc'
white = '#828bb8'

[colors.bright]
black = '#444a73'
red = '#ff757f'
green = '#c3e88d'
yellow = '#ffc777'
blue = '#82aaff'
magenta = '#c099ff'
cyan = '#86e1fc'
white = '#c8d3f5'

[[colors.indexed_colors]]
index = 16
color = '#ff966c'

[[colors.indexed_colors]]
index = 17
color = '#c53b53'

[cursor]
thickness = 0.3
unfocused_hollow = true

[cursor.style]
shape = "Block"
blinking = "On"

[font]
size = 10

[font.normal]
family = "JetBrainsMono NF"
style = "Medium"

[window]
decorations = "full"
dynamic_title = true
opacity = 1.0
startup_mode = "Windowed"
dynamic_padding = true

[window.dimensions]
columns = 100
lines = 30
