idle = true
fork = false
frame = "full"
vsync = true
title-hidden = true
mouse-cursor-icon = "arrow"
theme = "auto"
no-multigrid = false
srgb = false
tabs = true

[font]
normal = ["JetBrainsMono NF"]
size = 14
hinting = "full"
edging = "antialias"
