theme = "catppuccin_mocha"

[editor]
bufferline = "multiple"
color-modes = true
true-color = true
mouse = false
cursorline = false
line-number = "relative"
completion-replace = true

[editor.indent-guides]
render = true

[editor.cursor-shape]
insert = "bar"

[editor.statusline]
left = [
  "mode",
  "spacer",
  "version-control",
  "spacer",
  "file-name",
  "file-modification-indicator"
]
right = [
  "spinner",
  "spacer",
  "workspace-diagnostics",
  "spacer",
  "diagnostics",
  "position",
  "file-encoding",
  "file-line-ending",
  "file-type"
]
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"

[editor.lsp]
display-messages = true
