gui:
  showRandomTip: false
  showBottomLine: true
  nerdFontsVersion: "3"
  border: rounded
  theme:
    selectedLineBgColor:
      - "#7287fd"
    defaultFgColor:
      - "#cdd6f5"
    optionsTextColor:
      - "#89dceb"
    activeBorderColor:
      - "#b4befe"
      - bold
os:
  editPreset: "nvim"
