[terminal]
shell = "fish"

[window]
dynamic_padding = true
opacity = 0.8
blur = true
dimensions = { columns = 600, lines = 100 }

[cursor]
style = { shape = "Block" }
thickness = 0.2

[font]
normal = { family = "JetBrainsMono Nerd Font" }
size = 13

[mouse]
hide_when_typing = true
