theme = "tokyonight-night"

[editor]
line-number = "relative"
mouse = true
scrolloff = 4
cursorline = true
auto-format = false
true-color = true
undercurl = true
bufferline = "always"
color-modes = true
popup-border = "all"

[editor.statusline]
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"
left = ["mode", "version-control", "diagnostics", "file-name"]
center = []
right = ["file-encoding", "position", "position-percentage"]
separator = "│"

[editor.indent-guides]
render = true

[editor.file-picker]
hidden = true

[editor.soft-wrap]
enable = true

[editor.cursor-shape]
normal = "block"
insert = "bar"
select = "block"
