name: QA
on: [push, pull_request]

jobs:
  spellcheck:
    name: Spellcheck
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: crate-ci/typos@v1.19.0

  shellcheck:
     name: Shell check
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v4
       - uses: ludeeus/action-shellcheck@master
     
  
